# import library

In [2]:
import numpy as np

# create a relation from place name to place index

In [3]:

places = ['KLIA', 'Aquaria KLCC', 'KLCC', 'Pavilion', 'Melaka', 'Colmar Malaysia', 'Batu Caves', 'Cameron Highland',
          'Legoland', "Fraser's Hill", 'Genting Highland', 'Lost World of Tambun', 'Penang']

In [4]:
place2idx = {}
idx2place = {}

for i, place in enumerate(places):
    place2idx[place] = i
    idx2place[i] = place

print(place2idx)
print(idx2place)


{'KLIA': 0, 'Aquaria KLCC': 1, 'KLCC': 2, 'Pavilion': 3, 'Melaka': 4, 'Colmar Malaysia': 5, 'Batu Caves': 6, 'Cameron Highland': 7, 'Legoland': 8, "Fraser's Hill": 9, 'Genting Highland': 10, 'Lost World of Tambun': 11, 'Penang': 12}
{0: 'KLIA', 1: 'Aquaria KLCC', 2: 'KLCC', 3: 'Pavilion', 4: 'Melaka', 5: 'Colmar Malaysia', 6: 'Batu Caves', 7: 'Cameron Highland', 8: 'Legoland', 9: "Fraser's Hill", 10: 'Genting Highland', 11: 'Lost World of Tambun', 12: 'Penang'}


# define the adj matrix

In [5]:
adj_matrix = np.zeros((len(places), len(places))).astype(int)

adj_matrix[place2idx['KLIA'], place2idx['KLCC']] = 10
adj_matrix[place2idx['KLIA'], place2idx['Pavilion']] = 12
adj_matrix[place2idx['KLIA'], place2idx['Melaka']] = 50

adj_matrix[place2idx['Aquaria KLCC'], place2idx['KLCC']] = 2
adj_matrix[place2idx['KLCC'], place2idx['Aquaria KLCC']] = 2
adj_matrix[place2idx['KLCC'], place2idx['Pavilion']] = 5
adj_matrix[place2idx['Pavilion'], place2idx['KLCC']] = 5
adj_matrix[place2idx['Pavilion'], place2idx['Melaka']] = 60
adj_matrix[place2idx['Melaka'], place2idx['Pavilion']] = 60

adj_matrix[place2idx['KLCC'], place2idx['Batu Caves']] = 30
adj_matrix[place2idx['Batu Caves'], place2idx['KLCC']] = 30
adj_matrix[place2idx['Melaka'], place2idx['Legoland']] = 40
adj_matrix[place2idx['Legoland'], place2idx['Melaka']] = 40

adj_matrix[place2idx['Colmar Malaysia'], place2idx['Batu Caves']] = 10
adj_matrix[place2idx['Batu Caves'], place2idx['Colmar Malaysia']] = 10

adj_matrix[place2idx['Colmar Malaysia'], place2idx["Fraser's Hill"]] = 13
adj_matrix[place2idx["Fraser's Hill"], place2idx['Colmar Malaysia']] = 13
adj_matrix[place2idx['Batu Caves'], place2idx['Genting Highland']] = 15
adj_matrix[place2idx['Genting Highland'], place2idx['Batu Caves']] = 15
adj_matrix[place2idx['Cameron Highland'], place2idx['Genting Highland']] = 40
adj_matrix[place2idx['Genting Highland'], place2idx['Cameron Highland']] = 40
adj_matrix[place2idx['Cameron Highland'], place2idx['Lost World of Tambun']] = 15
adj_matrix[place2idx['Lost World of Tambun'], place2idx['Cameron Highland']] = 15

adj_matrix[place2idx["Fraser's Hill"], place2idx['Genting Highland']] = 15
adj_matrix[place2idx['Genting Highland'], place2idx["Fraser's Hill"]] = 15
adj_matrix[place2idx['Genting Highland'], place2idx['Lost World of Tambun']] = 60
adj_matrix[place2idx['Lost World of Tambun'], place2idx['Genting Highland']] = 60
adj_matrix[place2idx['Lost World of Tambun'], place2idx['Penang']] = 10
adj_matrix[place2idx['Penang'], place2idx['Lost World of Tambun']] = 10




In [6]:
print(adj_matrix)

[[ 0  0 10 12 50  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  5  0  0 30  0  0  0  0  0  0]
 [ 0  0  5  0 60  0  0  0  0  0  0  0  0]
 [ 0  0  0 60  0  0  0  0 40  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0 13  0  0  0]
 [ 0  0 30  0  0 10  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 40 15  0]
 [ 0  0  0  0 40  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 13  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0 15 40  0 15  0 60  0]
 [ 0  0  0  0  0  0  0 15  0  0 60  0 10]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0]]


In [34]:
def print_adj_matrix(adj_matrix):
    for i ,place in enumerate(places):
        print(i + 1, '=', place)
        
    print("adjacency matrix:")
    print('\\|', end='\t')
    for i in range (len(places)):
        print(i + 1, end='\t')
    print()
    print("_"*len(places) * 4)
    
    for i in range (len(places)):
        print(f'{i + 1}' + '|', end='\t')
        for num in adj_matrix[i,:]:
            print(num, end='\t')
        print()
        
        

print_adj_matrix(adj_matrix)

1 = KLIA
2 = Aquaria KLCC
3 = KLCC
4 = Pavilion
5 = Melaka
6 = Colmar Malaysia
7 = Batu Caves
8 = Cameron Highland
9 = Legoland
10 = Fraser's Hill
11 = Genting Highland
12 = Lost World of Tambun
13 = Penang
adjacency matrix:
\|	1	2	3	4	5	6	7	8	9	10	11	12	13	
____________________________________________________
1|	0	0	10	12	50	0	0	0	0	0	0	0	0	
2|	0	0	2	0	0	0	0	0	0	0	0	0	0	
3|	0	2	0	5	0	0	30	0	0	0	0	0	0	
4|	0	0	5	0	60	0	0	0	0	0	0	0	0	
5|	0	0	0	60	0	0	0	0	40	0	0	0	0	
6|	0	0	0	0	0	0	10	0	0	13	0	0	0	
7|	0	0	30	0	0	10	0	0	0	0	15	0	0	
8|	0	0	0	0	0	0	0	0	0	0	40	15	0	
9|	0	0	0	0	40	0	0	0	0	0	0	0	0	
10|	0	0	0	0	0	13	0	0	0	0	15	0	0	
11|	0	0	0	0	0	0	15	40	0	15	0	60	0	
12|	0	0	0	0	0	0	0	15	0	0	60	0	10	
13|	0	0	0	0	0	0	0	0	0	0	0	10	0	


## basic dfs

In [8]:
def dfs(adj_matrix, starting_place):
    stack = [place2idx[starting_place]]
    visited = set()
    visit_order = []
    while stack:
        place = stack.pop()
        if place not in visited:
            visit_order.append(place)
            visited.add(place)

            buffer_list = []
            for idx, cost in enumerate(adj_matrix[place]):
                if cost > 0:
                    buffer_list.append((cost, idx))

            buffer_list.sort(reverse=True)
            for pair in buffer_list:
                stack.append(pair[1])

    return visit_order


order = dfs(adj_matrix, 'KLIA')
for idx in order:
    print(idx2place[idx])

KLIA
KLCC
Aquaria KLCC
Pavilion
Melaka
Legoland
Batu Caves
Colmar Malaysia
Fraser's Hill
Genting Highland
Cameron Highland
Lost World of Tambun
Penang


## basic bfs

In [9]:
def bfs(adj_matrix, starting_place):
    queue = [place2idx[starting_place]]
    visited = set()
    visit_order = []
    while queue:
        place = queue.pop(0)
        if place not in visited:
            visit_order.append(place)
            visited.add(place)

            buffer_list = []
            for idx, cost in enumerate(adj_matrix[place]):
                if cost > 0:
                    buffer_list.append((cost, idx))

            buffer_list.sort()
            for pair in buffer_list:
                queue.append(pair[1])

    return visit_order


order = bfs(adj_matrix, 'KLIA')
for idx in order:
    print(idx2place[idx])

KLIA
KLCC
Pavilion
Melaka
Aquaria KLCC
Batu Caves
Legoland
Colmar Malaysia
Genting Highland
Fraser's Hill
Cameron Highland
Lost World of Tambun
Penang


## User preference dfs

In [10]:
def dfs_user(adj_matrix, starting_place):
    stack = [[(place2idx[starting_place], 0)]]
    visited = set()
    visit_order = []

    while stack:
        the_neighbors = stack.pop()

        buffer_list = []
        for place_n_cost in the_neighbors:
            if place_n_cost[0] not in visited:
                buffer_list.append(place_n_cost)

        selected_place_n_cost = None

        if len(buffer_list) == 1:
            selected_place_n_cost = buffer_list[0]


        elif len(buffer_list) > 1:
            while True:

                print(f'Based on DFS(User preference), after visiting {idx2place[visit_order[-1]]} you may visit next:')
                for i, pair in enumerate(buffer_list):
                    print(f'    {i + 1}- {idx2place[pair[0]]} ({pair[1]})')
                print()

                user_input = input('User input: ')
                if not user_input.isdigit():
                    print('Invalid data type inputted. Please try again.')
                    print()
                else:
                    user_input = int(user_input)

                    if user_input < 1 or user_input > len(buffer_list):
                        print('Invalid input, please try again')
                        print()
                    else:
                        print()
                        selected_place_n_cost = buffer_list[user_input - 1]
                        buffer_list.remove(selected_place_n_cost)
                        stack.append(buffer_list)
                        break

        if selected_place_n_cost is not None:
            visited.add(selected_place_n_cost[0])
            visit_order.append(selected_place_n_cost[0])

            neighbors = []

            for idx, cost in enumerate(adj_matrix[selected_place_n_cost[0]]):
                if cost > 0 and idx not in visited:
                    neighbors.append((idx, cost))

            stack.append(neighbors)

    return visit_order



In [11]:
order = dfs_user(adj_matrix, 'KLIA')
for idx in order:
    print(idx2place[idx])

Based on DFS(User preference), after visiting KLIA you may visit next:
    1- KLCC (10)
    2- Pavilion (12)
    3- Melaka (50)

Based on DFS(User preference), after visiting KLCC you may visit next:
    1- Aquaria KLCC (2)
    2- Pavilion (5)
    3- Batu Caves (30)


Based on DFS(User preference), after visiting Aquaria KLCC you may visit next:
    1- Pavilion (5)
    2- Batu Caves (30)

Based on DFS(User preference), after visiting Batu Caves you may visit next:
    1- Colmar Malaysia (10)
    2- Genting Highland (15)


Based on DFS(User preference), after visiting Genting Highland you may visit next:
    1- Cameron Highland (40)
    2- Lost World of Tambun (60)

KLIA
KLCC
Aquaria KLCC
Pavilion
Melaka
Legoland
Batu Caves
Colmar Malaysia
Fraser's Hill
Genting Highland
Cameron Highland
Lost World of Tambun
Penang


## user preference bfs

In [12]:
def bfs_user(adj_matrix, starting_place):
    queue = [place2idx[starting_place]]
    visited = set()
    visit_order = []
    while queue:
        place = queue.pop(0)
        if place not in visited:
            visit_order.append(place)
            visited.add(place)

            buffer_list = []
            for idx, cost in enumerate(adj_matrix[place]):
                if cost > 0 and idx not in visited and idx not in queue:
                    buffer_list.append(idx)

            while len(buffer_list) > 1:

                print(
                    f'Based on BFS(User preference), after visiting {idx2place[visit_order[-1]]} you may visit first:')
                for i, idx in enumerate(buffer_list):
                    print(f'    {i + 1}- {idx2place[idx]} ({adj_matrix[place, idx]})')
                print()

                user_input = input('User input: ')
                if not user_input.isdigit():
                    print('Invalid data type inputted. Please try again.')
                    print()
                else:
                    user_input = int(user_input)

                    if user_input < 1 or user_input > len(buffer_list):
                        print('Invalid input, please try again')
                        print()
                    else:
                        print()
                        enqueue_place = buffer_list[user_input - 1]
                        buffer_list.remove(enqueue_place)
                        queue.append(enqueue_place)

            if len(buffer_list) == 1:
                enqueue_place = buffer_list[0]
                queue.append(enqueue_place)

    return visit_order


In [13]:
order = bfs_user(adj_matrix, 'KLIA')
for idx in order:
    print(idx2place[idx])

Based on BFS(User preference), after visiting KLIA you may visit first:
    1- KLCC (10)
    2- Pavilion (12)
    3- Melaka (50)

Based on BFS(User preference), after visiting KLIA you may visit first:
    1- Pavilion (12)
    2- Melaka (50)


Based on BFS(User preference), after visiting KLCC you may visit first:
    1- Aquaria KLCC (2)
    2- Batu Caves (30)

Based on BFS(User preference), after visiting Batu Caves you may visit first:
    1- Colmar Malaysia (10)
    2- Genting Highland (15)


Based on BFS(User preference), after visiting Genting Highland you may visit first:
    1- Cameron Highland (40)
    2- Lost World of Tambun (60)

KLIA
KLCC
Pavilion
Melaka
Aquaria KLCC
Batu Caves
Legoland
Colmar Malaysia
Genting Highland
Fraser's Hill
Cameron Highland
Lost World of Tambun
Penang


# User interface 

In [31]:
inter_face_string = """
please select your method
1. basic dfs
2. basic bfs
3. user preference dfs
4. user preference bfs
"""
print("Welcome!\n")
print_adj_matrix(adj_matrix)
while True:
    print(inter_face_string)
    user_input = input('User input: ')
    if not user_input.isdigit():
        print('Invalid data type inputted. Please try again.')
        print()
    else:
        user_input = int(user_input)
        if 1 <= user_input <= 4:
            break
        else:
            print('Invalid input, please try again.')
    
order = None

if user_input == 1:
    order = dfs(adj_matrix, 'KLIA')
elif user_input == 2:
    order = bfs(adj_matrix, 'KLIA')
elif user_input == 3:
    order = dfs_user(adj_matrix, 'KLIA')
elif user_input == 4:
    order = bfs_user(adj_matrix, 'KLIA')

print()
print("the order is:")
for idx in order:
    print(idx2place[idx])
    




Welcome!

1 = KLIA
2 = Aquaria KLCC
3 = KLCC
4 = Pavilion
5 = Melaka
6 = Colmar Malaysia
7 = Batu Caves
8 = Cameron Highland
9 = Legoland
10 = Fraser's Hill
11 = Genting Highland
12 = Lost World of Tambun
13 = Penang
adjacency matrix:
\	1	2	3	4	5	6	7	8	9	10	11	12	13	
1	0	0	10	12	50	0	0	0	0	0	0	0	0	
2	0	0	2	0	0	0	0	0	0	0	0	0	0	
3	0	2	0	5	0	0	30	0	0	0	0	0	0	
4	0	0	5	0	60	0	0	0	0	0	0	0	0	
5	0	0	0	60	0	0	0	0	40	0	0	0	0	
6	0	0	0	0	0	0	10	0	0	13	0	0	0	
7	0	0	30	0	0	10	0	0	0	0	15	0	0	
8	0	0	0	0	0	0	0	0	0	0	40	15	0	
9	0	0	0	0	40	0	0	0	0	0	0	0	0	
10	0	0	0	0	0	13	0	0	0	0	15	0	0	
11	0	0	0	0	0	0	15	40	0	15	0	60	0	
12	0	0	0	0	0	0	0	15	0	0	60	0	10	
13	0	0	0	0	0	0	0	0	0	0	0	10	0	

please select your method
1. basic dfs
2. basic bfs
3. user preference dfs
4. user preference bfs

the order is:
KLIA
KLCC
Aquaria KLCC
Pavilion
Melaka
Legoland
Batu Caves
Colmar Malaysia
Fraser's Hill
Genting Highland
Cameron Highland
Lost World of Tambun
Penang
